spring:
  application:
    name: nxapi-gateway
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, nx
      routes:
        - id: api_route
          uri: http://localhost:8102
          predicates:
            - Path=/api/**

server:
  port: 8090

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace